changelog-type: ''
hash: fa8f601c85a75905fee45e29a98034939a4c2834076aeb668766baa05d04d10c
test-bench-deps:
  base: -any
  hspec: ! '>=1.3'
  monad-control: -any
  async: ! '>=2.0'
  lifted-base: ! '>=0.2'
  transformers-base: -any
  transformers: -any
  deepseq: -any
  QuickCheck: -any
synopsis: Catching all exceptions from within an enclosed computation
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  monad-control: -any
  async: ! '>=2.0'
  lifted-base: ! '>=0.2'
  transformers-base: -any
  transformers: -any
  deepseq: -any
all-versions:
- '1.0.0'
- '1.0.0.1'
- '1.0.0.2'
- '1.0.1'
- '1.0.1.1'
latest: '1.0.1.1'
description-type: haddock
description: ! 'Catching all exceptions raised within an enclosed computation,

  while remaining responsive to (external) asynchronous exceptions.

  For more information on the technique, please see:

  <https://www.fpcomplete.com/user/snoyberg/general-haskell/exceptions/catching-all-exceptions>'
